### ISSUE TITLE
Infinitely looping nodes

### ISSUE THREAD

**Issue by deflectn** [johannesvollmer/regex-nodes#4]
![Anmerkung 2019-05-16 065520](https://user-images.githubusercontent.com/5070798/57827439-a3088880-77a7-11e9-8444-6839d8d37e61.png)

**Comment by deflectn** [comment]
still possible

in the following Example the whole app crashes

![image](https://user-images.githubusercontent.com/5070798/57966659-5367bf80-7955-11e9-8447-d534c3b375a3.png)

the other example: only some of the nodes get unresponsive 

![image](https://user-images.githubusercontent.com/5070798/57966705-e6085e80-7955-11e9-9be5-112c6d5ca7c0.png)

**Comment by johannesvollmer** [comment]
Unresponsive Nodes is currently expected behaviour, they cannot be moved because touching them would result in displaying their infinite regular expression. That's because circles are in fact allowed, but only if they do not contribute to the regular expression. This is a UX problem which could be improved. 

However the app just crashing is a bug. Can you tell me more about what exactly happened?

**Comment by deflectn** [comment]
Maybe that was just caused by my escalating behavior for testing node editors. But as you can see in the first image: The editor freezes in the state of connecting the nodes.

**Comment by johannesvollmer** [comment]
![image](https://user-images.githubusercontent.com/32042925/57968123-ba41a480-7966-11e9-897e-5ba76dd8c0eb.png)
I was able to crash the application using this node setup.

Edit: I was able to cut it down to the following setup
![image](https://user-images.githubusercontent.com/32042925/57968180-5ec3e680-7967-11e9-84bb-79808e7b3741.png)

**Comment by johannesvollmer** [comment]
Ok I think I found the error. The algorithm works, but it is too generous, thus the detection takes too long. With the mentioned setup, it increases (probably exponentially) in computation time, depending on the node graph complexity. Lemme fix that

**Comment by johannesvollmer** [comment]
The "cycle detection" works by having a cost attached to each node while generating the regular expression, and cycles being infinite will always exceed the maximum cost. This means that overly complex (non-cyclic) nodes also will be rejected, and the message text currently incorrectly says it's because of cycles in the node graph. This will be improved later but it has a low priority.
